temurbek@dellserver:/data/projects/navbahor_erp$ cat docker-compose.yml
version: '3.8'

services:
  # Ma'lumotlar bazasi
  db:
    image: postgres:15-alpine
    container_name: erp_db
    restart: always
    environment:
      POSTGRES_USER: navbahor_admin
      POSTGRES_PASSWORD: "66068926Aa"
      POSTGRES_DB: navbahor_erp
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis (Kelajak uchun tayyor holatda)
  redis:
    image: redis:7-alpine
    container_name: erp_redis
    restart: always
    ports:
      - "6379:6379"

  # Backend (NestJS)
  api:
    build:
      context: ./erp-api
      dockerfile: Dockerfile
    container_name: erp_api
    restart: always
    privileged: true # USB portlarga kirish uchun
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Tarozi uchun (agar port boshqa bo'lsa o'zgartiriladi)
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=postgresql://navbahor_admin:66068926Aa@db:5432/navbahor_erp?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=navbahor_erp_ultra_secure_secret_key_2024_professional_cotton_factory_system
      - JWT_REFRESH_SECRET=navbahor_erp_refresh_token_ultra_secure_secret_key_2024
      - JWT_EXPIRES=24h
      - JWT_REFRESH_EXPIRES=7d
    expose:
      - "8080"
    depends_on:
      - db
      - redis

  # Frontend (Next.js)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://${DOMAIN_NAME}/api/v1
        - NEXT_PUBLIC_WS_URL=wss://${DOMAIN_NAME}
    container_name: erp_client
    restart: always
    expose:
      - "3100"
    depends_on:
      - api

  nginx:
    image: nginx:1.24-alpine
    container_name: erp_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - client
      - api

  certbot:
    image: certbot/certbot
    container_name: erp_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"